// Copyright (c) 2018-present The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <connectcoin-build-config.h> // IWYU pragma: keep

#include <common/args.h>
#include <init.h>
#include <qt/bitcoin.h>
#include <qt/guipreferences.h>
#include <qt/guiutil.h>
#include <qt/optionsdialog.h>
#include <qt/test/optiontests.h>
#include <test/util/setup_common.h>

#include <QCheckBox>
#include <QCoreApplication>
#include <QDataStream>
#include <QDataWidgetMapper>
#include <QSettings>
#include <QTemporaryDir>
#include <QTabWidget>
#include <QTest>
#include <QThread>
#include <QTimer>

#include <univalue.h>

#include <atomic>
#include <fstream>
#include <future>

namespace {
std::atomic<bool> settings_io_seen{false};
std::atomic<bool> settings_io_on_gui{false};
std::atomic<bool> block_settings_write{false};
std::atomic<bool> settings_write_entered{false};
std::atomic<bool> settings_write_timed_out{false};
std::atomic<size_t> settings_write_count{0};
std::atomic<bool> reject_settings_write{false};
std::shared_future<void> settings_write_release;

void RecordSettingsIoThread()
{
    settings_io_seen = true;
    if (QThread::currentThread() == QCoreApplication::instance()->thread()) settings_io_on_gui = true;
}

bool ReadTestSettings(QIODevice& device, QSettings::SettingsMap& values)
{
    RecordSettingsIoThread();
    QDataStream stream(&device);
    stream >> values;
    return stream.status() == QDataStream::Ok;
}

bool WriteTestSettings(QIODevice& device, const QSettings::SettingsMap& values)
{
    RecordSettingsIoThread();
    ++settings_write_count;
    if (block_settings_write.exchange(false)) {
        settings_write_entered = true;
        settings_write_timed_out = settings_write_release.wait_for(std::chrono::seconds{2}) != std::future_status::ready;
    }
    if (reject_settings_write.load()) return false;
    QDataStream stream(&device);
    stream << values;
    return stream.status() == QDataStream::Ok;
}
} // namespace

OptionTests::OptionTests(interfaces::Node& node) : m_node(node)
{
    gArgs.LockSettings([&](common::Settings& s) { m_previous_settings = s; });
}

void OptionTests::init()
{
    // reset args
    gArgs.LockSettings([&](common::Settings& s) { s = m_previous_settings; });
    gArgs.ClearPathCache();
}

void OptionTests::migrateSettings()
{
    // Set legacy QSettings and verify that they get cleared and migrated to
    // settings.json
    QSettings settings;
    settings.setValue("nDatabaseCache", 600);
    settings.setValue("nThreadsScriptVerif", 12);
    settings.setValue("fListen", false);
    settings.setValue("bPrune", true);
    settings.setValue("nPruneSize", 3);
    settings.setValue("fUseProxy", true);
    settings.setValue("addrProxy", "proxy:123");
    settings.setValue("fUseSeparateProxyTor", true);
    settings.setValue("addrSeparateProxyTor", "onion:234");

    settings.sync();

    QVERIFY(settings.contains("nDatabaseCache"));
    QVERIFY(settings.contains("nThreadsScriptVerif"));
    QVERIFY(settings.contains("fListen"));
    QVERIFY(settings.contains("bPrune"));
    QVERIFY(settings.contains("nPruneSize"));
    QVERIFY(settings.contains("fUseProxy"));
    QVERIFY(settings.contains("addrProxy"));
    QVERIFY(settings.contains("fUseSeparateProxyTor"));
    QVERIFY(settings.contains("addrSeparateProxyTor"));

    OptionsModel options{m_node};
    bilingual_str error;
    QVERIFY(options.Init(error));
    QVERIFY(!settings.contains("nDatabaseCache"));
    QVERIFY(!settings.contains("nThreadsScriptVerif"));
    QVERIFY(!settings.contains("fListen"));
    QVERIFY(!settings.contains("bPrune"));
    QVERIFY(!settings.contains("nPruneSize"));
    QVERIFY(!settings.contains("fUseProxy"));
    QVERIFY(!settings.contains("addrProxy"));
    QVERIFY(!settings.contains("fUseSeparateProxyTor"));
    QVERIFY(!settings.contains("addrSeparateProxyTor"));

    std::ifstream file((gArgs.GetDataDirNet() / "settings.json").std_path());
    std::string default_warning = strprintf("This file is automatically generated and updated by %s. Please do not edit this file while the node "
                                            "is running, as any changes might be ignored or overwritten.",
                                            CLIENT_NAME);
    QCOMPARE(std::string(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()).c_str(), "{\n"
        "    \"_warning_\": \""+ default_warning+"\",\n"
        "    \"dbcache\": \"600\",\n"
        "    \"listen\": false,\n"
        "    \"onion\": \"onion:234\",\n"
        "    \"par\": \"12\",\n"
        "    \"proxy\": \"proxy:123\",\n"
        "    \"prune\": \"2861\"\n"
        "}\n");
}

void OptionTests::integerGetArgBug()
{
    // Test regression https://github.com/bitcoin/bitcoin/issues/24457. Ensure
    // that setting integer prune value doesn't cause an exception to be thrown
    // in the OptionsModel constructor
    gArgs.LockSettings([&](common::Settings& settings) {
        settings.forced_settings.erase("prune");
        settings.rw_settings["prune"] = 3814;
    });
    gArgs.WriteSettingsFile();
    bilingual_str error;
    QVERIFY(OptionsModel{m_node}.Init(error));
    gArgs.LockSettings([&](common::Settings& settings) {
        settings.rw_settings.erase("prune");
    });
    gArgs.WriteSettingsFile();
}

void OptionTests::parametersInteraction()
{
    // Test that the bug https://github.com/bitcoin-core/gui/issues/567 does not resurface.
    // It was fixed via https://github.com/bitcoin-core/gui/pull/568.
    // With fListen=false in ~/.config/ConnectCoin/ConnectCoin-Qt.conf and all else left as default,
    // connectcoin-qt should set both -listen and -listenonion to false and start successfully.
    gArgs.LockSettings([&](common::Settings& s) {
        s.forced_settings.erase("listen");
        s.forced_settings.erase("listenonion");
    });
    QVERIFY(!gArgs.IsArgSet("-listen"));
    QVERIFY(!gArgs.IsArgSet("-listenonion"));

    QSettings settings;
    settings.setValue("fListen", false);

    bilingual_str error;
    QVERIFY(OptionsModel{m_node}.Init(error));

    const bool expected{false};

    QVERIFY(gArgs.IsArgSet("-listen"));
    QCOMPARE(gArgs.GetBoolArg("-listen", !expected), expected);

    QVERIFY(gArgs.IsArgSet("-listenonion"));
    QCOMPARE(gArgs.GetBoolArg("-listenonion", !expected), expected);

    QVERIFY(AppInitParameterInteraction(gArgs));

    // cleanup
    settings.remove("fListen");
    QVERIFY(!settings.contains("fListen"));
    gArgs.ClearPathCache();
}

void OptionTests::popupNotifications()
{
    QSettings settings;
    settings.remove("fPopupNotifications");
    bilingual_str error;
    OptionsModel options{m_node};
    QVERIFY(options.Init(error));
    QVERIFY(!options.getPopupNotifications());
    QVERIFY(!options.isPopupNotificationsOverridden());
    const auto index{options.index(OptionsModel::PopupNotifications, 0)};
    QCOMPARE(options.data(index, Qt::EditRole).toBool(), false);

    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&options);
        auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        QVERIFY(checkbox);
        QVERIFY(checkbox->isEnabled());
        QVERIFY(!checkbox->isChecked());
        // Display is available on macOS too, unlike the Window tab.
        auto* tabs = dialog.findChild<QTabWidget*>("tabWidget");
        QVERIFY(tabs);
        QVERIFY(tabs->indexOf(dialog.findChild<QWidget*>("tabDisplay")) >= 0);
        checkbox->setChecked(true);
        QVERIFY(QMetaObject::invokeMethod(&dialog, "on_cancelButton_clicked"));
        QVERIFY(!options.getPopupNotifications());
    }
    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&options);
        auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        auto* mapper = dialog.findChild<QDataWidgetMapper*>();
        QVERIFY(checkbox);
        QVERIFY(mapper);
        QCOMPARE(mapper->mappedWidgetAt(OptionsModel::PopupNotifications), checkbox);
        // Exercise the actual OK handler without applying unrelated options
        // such as OS auto-start registration or port mapping during the test.
        mapper->clearMapping();
        mapper->addMapping(checkbox, OptionsModel::PopupNotifications);
        checkbox->setChecked(true);
        QVERIFY(QMetaObject::invokeMethod(&dialog, "on_okButton_clicked"));
        QVERIFY(options.getPopupNotifications());
        GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
        QVERIFY(settings.value("fPopupNotifications").toBool());
        QVERIFY(!options.isRestartRequired());
    }

    OptionsModel reloaded{m_node};
    QVERIFY(reloaded.Init(error));
    QVERIFY(reloaded.getPopupNotifications());
    QVERIFY(reloaded.setOption(OptionsModel::PopupNotifications, false));
    QVERIFY(!reloaded.getPopupNotifications());
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    QVERIFY(!settings.value("fPopupNotifications").toBool());

    // Config opts in even with a saved false preference; CLI overrides config.
    gArgs.LockSettings([](common::Settings& s) { s.ro_config[""]["popupnotifications"] = {"1"}; });
    OptionsModel configured{m_node};
    QVERIFY(configured.Init(error));
    QVERIFY(configured.getPopupNotifications());
    QVERIFY(configured.isPopupNotificationsOverridden());
    QVERIFY(configured.getOverriddenByCommandLine().contains("-popupnotifications=1"));
    {
        // Passive reads must not wait for the settings mutex held by a slow
        // settings.json write. Bound the worker wait so regressions fail rather
        // than deadlocking the test process.
        std::promise<void> locked;
        auto acquired = locked.get_future();
        std::promise<void> release;
        auto released = release.get_future();
        std::atomic<bool> timed_out{false};
        auto writer = std::async(std::launch::async, [&] {
            gArgs.LockSettings([&](common::Settings&) {
                locked.set_value();
                timed_out = released.wait_for(std::chrono::seconds{2}) != std::future_status::ready;
            });
        });
        acquired.wait();
        const auto popup = configured.getPopupNotifications();
        const auto overridden = configured.isPopupNotificationsOverridden();
        const auto database_cache = configured.getOption(OptionsModel::DatabaseCache);
        const auto signer = configured.hasSigner();
        release.set_value();
        writer.get();
        QVERIFY(!timed_out);
        QVERIFY(popup);
        QVERIFY(overridden);
        QVERIFY(database_cache.isValid());
        QCOMPARE(signer, configured.hasSigner());
    }
    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&configured);
        const auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        QVERIFY(checkbox);
        QVERIFY(checkbox->isChecked());
        QVERIFY(!checkbox->isEnabled());
    }
    QVERIFY(configured.setOption(OptionsModel::PopupNotifications, false));
    QVERIFY(configured.getPopupNotifications());
    gArgs.LockSettings([](common::Settings& s) { s.command_line_options["popupnotifications"] = {false}; });
    // Command-line/config overrides are startup state. Notification callbacks
    // keep the snapshot and never take the settings-file writer's lock.
    QVERIFY(configured.getPopupNotifications());
    OptionsModel command_line{m_node};
    QVERIFY(command_line.Init(error));
    QVERIFY(!command_line.getPopupNotifications());
    QVERIFY(!command_line.getOption(OptionsModel::PopupNotifications).toBool());
    // An explicit 0 must also override an existing GUI opt-in.
    settings.setValue("fPopupNotifications", true);
    OptionsModel disabled{m_node};
    QVERIFY(disabled.Init(error));
    QVERIFY(!disabled.getPopupNotifications());
    gArgs.LockSettings([&](common::Settings& s) { s = m_previous_settings; });
    settings.remove("fPopupNotifications");
}

void OptionTests::extractFilter()
{
    QString filter = QString("Partially Signed Transaction (Binary) (*.psbt)");
    QCOMPARE(GUIUtil::ExtractFirstSuffixFromFilter(filter), "psbt");

    filter = QString("Image (*.png *.jpg)");
    QCOMPARE(GUIUtil::ExtractFirstSuffixFromFilter(filter), "png");
}

void OptionTests::settingsIoOffGui()
{
    QTemporaryDir directory;
    QVERIFY(directory.isValid());
    const auto format = QSettings::registerFormat("qt-options-worker-test", ReadTestSettings, WriteTestSettings);
    QVERIFY(format != QSettings::InvalidFormat);
    QSettings::setPath(format, QSettings::UserScope, directory.path());
    struct RestoreFormat {
        QSettings::Format previous{QSettings::defaultFormat()};
        ~RestoreFormat() { QSettings::setDefaultFormat(previous); }
    } restore;
    QSettings::setDefaultFormat(format);
    settings_io_seen = false;
    settings_io_on_gui = false;

    bilingual_str error;
    OptionsModel options{m_node};
    QVERIFY(options.Init(error));
    QVERIFY(options.setOption(OptionsModel::PopupNotifications, true));
    QVERIFY(options.setOption(OptionsModel::MaskValues, true));
    options.setRestartRequired(true);
    QVERIFY(options.isRestartRequired());
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    QVERIFY(settings_io_seen.load());
    QVERIFY2(!settings_io_on_gui.load(), "Options initialization or persistence accessed QSettings storage on the GUI thread");
}

void OptionTests::cachedGuiPreferences()
{
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    QTemporaryDir directory;
    QVERIFY(directory.isValid());
    const auto format = QSettings::registerFormat("qt-gui-preferences-test", ReadTestSettings, WriteTestSettings);
    QVERIFY(format != QSettings::InvalidFormat);
    QSettings::setPath(format, QSettings::UserScope, directory.path());
    struct RestoreIdentity {
        QSettings::Format format{QSettings::defaultFormat()};
        QString application{QCoreApplication::applicationName()};
        ~RestoreIdentity()
        {
            QSettings::setDefaultFormat(format);
            QCoreApplication::setApplicationName(application);
        }
    } restore;
    QSettings::setDefaultFormat(format);
    QCoreApplication::setApplicationName("gui-preferences-main");
    GuiSettings main;
    GUIUtil::WaitForBackendTask(main.load());
    settings_io_seen = false;
    settings_io_on_gui = false;
    settings_write_entered = false;
    settings_write_timed_out = false;
    settings_write_count = 0;
    std::promise<void> release;
    settings_write_release = release.get_future().share();
    block_settings_write = true;
    main.setValue("held", true);
    QTRY_VERIFY(settings_write_entered.load());
    auto reload_during_edits = main.load(/*reload=*/true);

    // A stalled QSettings callback must not hold the cache lock. Reads, writes
    // and destruction of the widget-facing facade all finish before release.
    {
        GuiSettings widget_preferences;
        QVERIFY(widget_preferences.value("held").toBool());
        for (int value = 0; value < 1000; ++value) widget_preferences.setValue("geometry", value);
        QCOMPARE(widget_preferences.value("geometry").toInt(), 999);
        widget_preferences.setValue("discard/child", 7);
        widget_preferences.remove("discard");
        QVERIFY(!widget_preferences.contains("discard/child"));
    }
    QCOMPARE(settings_write_count.load(), size_t{1});
    QVERIFY(!settings_write_timed_out.load());

    // Loading a second network is an explicit responsive startup operation.
    // Previously queued writes retain their original application identity.
    QCoreApplication::setApplicationName("gui-preferences-testnet");
    GuiSettings testnet;
    bool heartbeat_fired{false};
    QTimer heartbeat;
    heartbeat.setSingleShot(true);
    QObject::connect(&heartbeat, &QTimer::timeout, &heartbeat, [&] {
        heartbeat_fired = true;
        release.set_value();
    });
    heartbeat.start(25);
    GUIUtil::WaitForBackendTask(testnet.load());
    GUIUtil::WaitForBackendTask(std::move(reload_during_edits));
    heartbeat.stop();
    if (!heartbeat_fired) release.set_value();
    QVERIFY(heartbeat_fired);
    QVERIFY(!settings_write_timed_out.load());
    QVERIFY(!testnet.contains("geometry"));
    QCOMPARE(main.value("geometry").toInt(), 999);
    // 1000 updates of one key must coalesce into a single pending write batch.
    QCOMPARE(settings_write_count.load(), size_t{2});
    testnet.setValue("geometry", 42);
    main.setValue("geometry", 1001);
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    GUIUtil::WaitForBackendTask(main.load(/*reload=*/true));
    GUIUtil::WaitForBackendTask(testnet.load(/*reload=*/true));
    QCOMPARE(main.value("geometry").toInt(), 1001);
    QCOMPARE(testnet.value("geometry").toInt(), 42);
    QVERIFY(!main.contains("discard/child"));
    reject_settings_write = true;
    main.setValue("retry", 15);
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    const auto failed_writes = settings_write_count.load();
    QCOMPARE(main.value("retry").toInt(), 15);
    reject_settings_write = false;
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
    QVERIFY(settings_write_count.load() > failed_writes);
    GUIUtil::WaitForBackendTask(main.load(/*reload=*/true));
    QCOMPARE(main.value("retry").toInt(), 15);
    QVERIFY(settings_io_seen.load());
    QVERIFY2(!settings_io_on_gui.load(), "GUI preferences touched persistent storage on the GUI thread");

    main.clear();
    testnet.clear();
    GUIUtil::WaitForBackendTask(GuiPreferences::Flush());
}
