// Copyright (c) 2018-present The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <connectcoin-build-config.h> // IWYU pragma: keep

#include <common/args.h>
#include <init.h>
#include <qt/bitcoin.h>
#include <qt/guiutil.h>
#include <qt/optionsdialog.h>
#include <qt/test/optiontests.h>
#include <test/util/setup_common.h>

#include <QCheckBox>
#include <QDataWidgetMapper>
#include <QSettings>
#include <QTabWidget>
#include <QTest>

#include <univalue.h>

#include <fstream>

OptionTests::OptionTests(interfaces::Node& node) : m_node(node)
{
    gArgs.LockSettings([&](common::Settings& s) { m_previous_settings = s; });
}

void OptionTests::init()
{
    // reset args
    gArgs.LockSettings([&](common::Settings& s) { s = m_previous_settings; });
    gArgs.ClearPathCache();
}

void OptionTests::migrateSettings()
{
    // Set legacy QSettings and verify that they get cleared and migrated to
    // settings.json
    QSettings settings;
    settings.setValue("nDatabaseCache", 600);
    settings.setValue("nThreadsScriptVerif", 12);
    settings.setValue("fListen", false);
    settings.setValue("bPrune", true);
    settings.setValue("nPruneSize", 3);
    settings.setValue("fUseProxy", true);
    settings.setValue("addrProxy", "proxy:123");
    settings.setValue("fUseSeparateProxyTor", true);
    settings.setValue("addrSeparateProxyTor", "onion:234");

    settings.sync();

    QVERIFY(settings.contains("nDatabaseCache"));
    QVERIFY(settings.contains("nThreadsScriptVerif"));
    QVERIFY(settings.contains("fListen"));
    QVERIFY(settings.contains("bPrune"));
    QVERIFY(settings.contains("nPruneSize"));
    QVERIFY(settings.contains("fUseProxy"));
    QVERIFY(settings.contains("addrProxy"));
    QVERIFY(settings.contains("fUseSeparateProxyTor"));
    QVERIFY(settings.contains("addrSeparateProxyTor"));

    OptionsModel options{m_node};
    bilingual_str error;
    QVERIFY(options.Init(error));
    QVERIFY(!settings.contains("nDatabaseCache"));
    QVERIFY(!settings.contains("nThreadsScriptVerif"));
    QVERIFY(!settings.contains("fListen"));
    QVERIFY(!settings.contains("bPrune"));
    QVERIFY(!settings.contains("nPruneSize"));
    QVERIFY(!settings.contains("fUseProxy"));
    QVERIFY(!settings.contains("addrProxy"));
    QVERIFY(!settings.contains("fUseSeparateProxyTor"));
    QVERIFY(!settings.contains("addrSeparateProxyTor"));

    std::ifstream file((gArgs.GetDataDirNet() / "settings.json").std_path());
    std::string default_warning = strprintf("This file is automatically generated and updated by %s. Please do not edit this file while the node "
                                            "is running, as any changes might be ignored or overwritten.",
                                            CLIENT_NAME);
    QCOMPARE(std::string(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()).c_str(), "{\n"
        "    \"_warning_\": \""+ default_warning+"\",\n"
        "    \"dbcache\": \"600\",\n"
        "    \"listen\": false,\n"
        "    \"onion\": \"onion:234\",\n"
        "    \"par\": \"12\",\n"
        "    \"proxy\": \"proxy:123\",\n"
        "    \"prune\": \"2861\"\n"
        "}\n");
}

void OptionTests::integerGetArgBug()
{
    // Test regression https://github.com/bitcoin/bitcoin/issues/24457. Ensure
    // that setting integer prune value doesn't cause an exception to be thrown
    // in the OptionsModel constructor
    gArgs.LockSettings([&](common::Settings& settings) {
        settings.forced_settings.erase("prune");
        settings.rw_settings["prune"] = 3814;
    });
    gArgs.WriteSettingsFile();
    bilingual_str error;
    QVERIFY(OptionsModel{m_node}.Init(error));
    gArgs.LockSettings([&](common::Settings& settings) {
        settings.rw_settings.erase("prune");
    });
    gArgs.WriteSettingsFile();
}

void OptionTests::parametersInteraction()
{
    // Test that the bug https://github.com/bitcoin-core/gui/issues/567 does not resurface.
    // It was fixed via https://github.com/bitcoin-core/gui/pull/568.
    // With fListen=false in ~/.config/ConnectCoin/ConnectCoin-Qt.conf and all else left as default,
    // connectcoin-qt should set both -listen and -listenonion to false and start successfully.
    gArgs.LockSettings([&](common::Settings& s) {
        s.forced_settings.erase("listen");
        s.forced_settings.erase("listenonion");
    });
    QVERIFY(!gArgs.IsArgSet("-listen"));
    QVERIFY(!gArgs.IsArgSet("-listenonion"));

    QSettings settings;
    settings.setValue("fListen", false);

    bilingual_str error;
    QVERIFY(OptionsModel{m_node}.Init(error));

    const bool expected{false};

    QVERIFY(gArgs.IsArgSet("-listen"));
    QCOMPARE(gArgs.GetBoolArg("-listen", !expected), expected);

    QVERIFY(gArgs.IsArgSet("-listenonion"));
    QCOMPARE(gArgs.GetBoolArg("-listenonion", !expected), expected);

    QVERIFY(AppInitParameterInteraction(gArgs));

    // cleanup
    settings.remove("fListen");
    QVERIFY(!settings.contains("fListen"));
    gArgs.ClearPathCache();
}

void OptionTests::popupNotifications()
{
    QSettings settings;
    settings.remove("fPopupNotifications");
    bilingual_str error;
    OptionsModel options{m_node};
    QVERIFY(options.Init(error));
    QVERIFY(!options.getPopupNotifications());
    QVERIFY(!options.isPopupNotificationsOverridden());
    const auto index{options.index(OptionsModel::PopupNotifications, 0)};
    QCOMPARE(options.data(index, Qt::EditRole).toBool(), false);

    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&options);
        auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        QVERIFY(checkbox);
        QVERIFY(checkbox->isEnabled());
        QVERIFY(!checkbox->isChecked());
        // Display is available on macOS too, unlike the Window tab.
        auto* tabs = dialog.findChild<QTabWidget*>("tabWidget");
        QVERIFY(tabs);
        QVERIFY(tabs->indexOf(dialog.findChild<QWidget*>("tabDisplay")) >= 0);
        checkbox->setChecked(true);
        QVERIFY(QMetaObject::invokeMethod(&dialog, "on_cancelButton_clicked"));
        QVERIFY(!options.getPopupNotifications());
    }
    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&options);
        auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        auto* mapper = dialog.findChild<QDataWidgetMapper*>();
        QVERIFY(checkbox);
        QVERIFY(mapper);
        QCOMPARE(mapper->mappedWidgetAt(OptionsModel::PopupNotifications), checkbox);
        // Exercise the actual OK handler without applying unrelated options
        // such as OS auto-start registration or port mapping during the test.
        mapper->clearMapping();
        mapper->addMapping(checkbox, OptionsModel::PopupNotifications);
        checkbox->setChecked(true);
        QVERIFY(QMetaObject::invokeMethod(&dialog, "on_okButton_clicked"));
        QVERIFY(options.getPopupNotifications());
        QVERIFY(settings.value("fPopupNotifications").toBool());
        QVERIFY(!options.isRestartRequired());
    }

    OptionsModel reloaded{m_node};
    QVERIFY(reloaded.Init(error));
    QVERIFY(reloaded.getPopupNotifications());
    QVERIFY(reloaded.setOption(OptionsModel::PopupNotifications, false));
    QVERIFY(!reloaded.getPopupNotifications());
    QVERIFY(!settings.value("fPopupNotifications").toBool());

    // Config opts in even with a saved false preference; CLI overrides config.
    gArgs.LockSettings([](common::Settings& s) { s.ro_config[""]["popupnotifications"] = {"1"}; });
    OptionsModel configured{m_node};
    QVERIFY(configured.Init(error));
    QVERIFY(configured.getPopupNotifications());
    QVERIFY(configured.isPopupNotificationsOverridden());
    QVERIFY(configured.getOverriddenByCommandLine().contains("-popupnotifications=1"));
    {
        OptionsDialog dialog{nullptr, false};
        dialog.setModel(&configured);
        const auto* checkbox = dialog.findChild<QCheckBox*>("popupNotifications");
        QVERIFY(checkbox);
        QVERIFY(checkbox->isChecked());
        QVERIFY(!checkbox->isEnabled());
    }
    QVERIFY(configured.setOption(OptionsModel::PopupNotifications, false));
    QVERIFY(configured.getPopupNotifications());
    gArgs.LockSettings([](common::Settings& s) { s.command_line_options["popupnotifications"] = {false}; });
    QVERIFY(!configured.getPopupNotifications());
    QVERIFY(!configured.getOption(OptionsModel::PopupNotifications).toBool());
    // An explicit 0 must also override an existing GUI opt-in.
    settings.setValue("fPopupNotifications", true);
    OptionsModel disabled{m_node};
    QVERIFY(disabled.Init(error));
    QVERIFY(!disabled.getPopupNotifications());
    gArgs.LockSettings([&](common::Settings& s) { s = m_previous_settings; });
    settings.remove("fPopupNotifications");
}

void OptionTests::extractFilter()
{
    QString filter = QString("Partially Signed Transaction (Binary) (*.psbt)");
    QCOMPARE(GUIUtil::ExtractFirstSuffixFromFilter(filter), "psbt");

    filter = QString("Image (*.png *.jpg)");
    QCOMPARE(GUIUtil::ExtractFirstSuffixFromFilter(filter), "png");
}
