#!/usr/bin/env python3
# Copyright (c) 2024-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Convert a ConnectCoin typed-output UTXO snapshot to a SQLite3 database.

The input UTXO set can be generated by ConnectCoin Core with the `dumptxoutset` RPC:
$ connectcoin-cli dumptxoutset ~/utxos.dat latest

The created database contains a table `utxos` with the following schema:
(txid TEXT, vout INT, value INT, coinbase INT, height INT, scriptpubkey TEXT)

If --txid=raw or --txid=rawle is specified, txid will be BLOB instead;
if --spk=raw, then scriptpubkey will be BLOB instead.

scriptpubkey is Core's compatibility view, not a Bitcoin script on the wire:
type 1 is 0x5120 || x-only public key; type 2 is 0x52 || domain length (u8)
|| domain || work target (32-byte little endian) || root version (u32 little
endian) || signature algorithms mask (u8). Bitcoin's legacy compressed-script
snapshots are not supported.
This checks the snapshot encoding, not its chain membership or consensus validity.
"""
import argparse
from functools import lru_cache
import os
import sqlite3
import sys
import tempfile
import time


UTXO_DUMP_MAGIC = b'utxo\xff'
UTXO_DUMP_VERSION = 2
MAX_MONEY = 100_000_000 * 10**10
# Snapshot counts/vouts use ReadCompactSize with its default range check.
MAX_COMPACT_SIZE = 0x04000000
NET_MAGIC_BYTES = {
    b"\xd9\x51\xa5\xe2": "ConnectCoin Mainnet (not launched)",
    b"\x30\x4c\x2f\x0c": "ConnectCoin Signet (P2C mask v1)",
    b"\xc7\x29\x1f\xf5": "ConnectCoin Testnet3 (P2C mask v1)",
    b"\x77\xd6\x6c\xbc": "ConnectCoin Testnet4 (P2C mask v1)",
    b"\x3a\xf8\x3b\xe3": "ConnectCoin Regtest (P2C mask v1)",
}


def read_exact(f, size, field):
    data = f.read(size)
    if len(data) != size:
        raise ValueError(f"truncated {field}: expected {size} bytes, got {len(data)}")
    return data


def read_varint(f, maximum=(1 << 64) - 1):
    """Equivalent of `ReadVarInt()` (see serialization module)."""
    n = 0
    while True:
        dat = read_exact(f, 1, "VARINT")[0]
        n = (n << 7) | (dat & 0x7f)
        if (dat & 0x80) > 0:
            n += 1
        if n > maximum:
            raise ValueError("VARINT overflow")
        if not dat & 0x80:
            return n


def read_compactsize(f, maximum=MAX_COMPACT_SIZE):
    """Equivalent of `ReadCompactSize()` (see serialization module)."""
    marker = read_exact(f, 1, "CompactSize")[0]
    n = marker
    if marker >= 253:
        width, minimum = {253: (2, 253), 254: (4, 0x10000), 255: (8, 0x100000000)}[marker]
        n = int.from_bytes(read_exact(f, width, "CompactSize"), "little")
        if n < minimum:
            raise ValueError("non-canonical CompactSize")
    if n > maximum:
        raise ValueError("CompactSize out of range")
    return n


def decompress_amount(x):
    """Equivalent of `DecompressAmount()` (see compressor module)."""
    if x == 0:
        return 0
    x -= 1
    e = x % 10
    x //= 10
    n = 0
    if e < 9:
        d = (x % 9) + 1
        x //= 9
        n = x * 10 + d
    else:
        n = x + 1
    while e > 0:
        n *= 10
        e -= 1
    return n


@lru_cache(maxsize=4096)
def validate_pubkey(pubkey):
    """Match Core's x-only key check; bound caching for repeated output keys."""
    field = 2**256 - 2**32 - 977
    x = int.from_bytes(pubkey, 'big')
    rhs = (x**3 + 7) % field
    if x >= field or pow(pow(rhs, (field + 1) // 4, field), 2, field) != rhs:
        raise ValueError("invalid P2PK x-only public key")


def read_typed_output(f):
    """Read CTxOut::UnserializePayload and return its compatibility view."""
    output_type = read_exact(f, 1, "output type")[0]
    if output_type == 1:
        pubkey = read_exact(f, 32, "P2PK public key")
        validate_pubkey(pubkey)
        return b'\x51\x20' + pubkey
    if output_type != 2:
        raise ValueError(f"invalid or unknown output type {output_type}")

    domain_size = read_exact(f, 1, "P2C domain length")
    domain = read_exact(f, domain_size[0], "P2C domain")
    if not 1 <= len(domain) <= 253:
        raise ValueError("invalid P2C domain length")
    for label in domain.split(b'.'):
        if (not 1 <= len(label) <= 63 or label.startswith(b'-') or label.endswith(b'-') or
                any(not (97 <= ch <= 122 or 48 <= ch <= 57 or ch == 45) for ch in label)):
            raise ValueError("invalid P2C domain: expected canonical lower-case ASCII")
    target = read_exact(f, 32, "P2C work target")
    roots = read_exact(f, 4, "P2C root certificate version")
    if int.from_bytes(roots, 'little') == 0:
        raise ValueError("invalid P2C root certificate version")
    mask = read_exact(f, 1, "P2C signature algorithms mask")
    if not 1 <= mask[0] <= 7:
        raise ValueError("invalid P2C signature algorithms mask")
    return b'\x52' + domain_size + domain + target + roots + mask


def convert(f, con, args):
    magic_bytes = read_exact(f, 5, "snapshot magic")
    version = int.from_bytes(read_exact(f, 2, "snapshot version"), 'little')
    network_magic = read_exact(f, 4, "network magic")
    block_hash = read_exact(f, 32, "block hash")
    num_utxos = int.from_bytes(read_exact(f, 8, "UTXO count"), 'little')
    if magic_bytes != UTXO_DUMP_MAGIC:
        raise ValueError("input is not a UTXO snapshot")
    if version != UTXO_DUMP_VERSION:
        raise ValueError(f"unknown UTXO snapshot version {version} (only {UTXO_DUMP_VERSION} supported)")
    network_string = NET_MAGIC_BYTES.get(network_magic, f"unknown network ({network_magic.hex()})")
    print(f"UTXO Snapshot for {network_string} at block hash "
          f"{block_hash[::-1].hex()[:32]}..., contains {num_utxos} coins")

    spk_hex = args.spk == 'hex'
    txid_hex = args.txid == 'hex'
    txid_reverse = args.txid != 'raw'
    txid_fmt = "TEXT" if txid_hex else "BLOB"
    spk_fmt = "TEXT" if spk_hex else "BLOB"
    con.execute(f"CREATE TABLE utxos(txid {txid_fmt}, vout INT, value INT, coinbase INT, height INT, scriptpubkey {spk_fmt})")

    start_time = time.monotonic()
    write_batch = []
    coins_per_hash_left = 0
    max_height = 0
    for coin_idx in range(1, num_utxos + 1):
        if coins_per_hash_left == 0:
            prevout_hash = read_exact(f, 32, "transaction hash")
            coins_per_hash_left = read_compactsize(f)
            if not 1 <= coins_per_hash_left <= num_utxos - coin_idx + 1:
                raise ValueError("invalid coins-per-transaction count")
            txid_write = prevout_hash[::-1] if txid_reverse else prevout_hash
            txid_write = txid_write.hex() if txid_hex else txid_write
        prevout_index = read_compactsize(f)
        code = read_varint(f, maximum=0xffffffff)
        height = code >> 1
        is_coinbase = code & 1
        amount = decompress_amount(read_varint(f))
        if amount > MAX_MONEY:
            raise ValueError("output amount exceeds MAX_MONEY")
        scriptpubkey = read_typed_output(f)
        scriptpubkey_write = scriptpubkey.hex() if spk_hex else scriptpubkey
        write_batch.append((txid_write, prevout_index, amount, is_coinbase, height, scriptpubkey_write))
        max_height = max(max_height, height)
        coins_per_hash_left -= 1

        if args.verbose:
            print(f"Coin {coin_idx}/{num_utxos}:")
            print(f"    prevout = {prevout_hash[::-1].hex()}:{prevout_index}")
            print(f"    amount = {amount}, height = {height}, coinbase = {is_coinbase}")
            print(f"    scriptPubKey = {scriptpubkey.hex()}\n")

        if len(write_batch) == 16 * 1024 or coin_idx == num_utxos:
            con.executemany("INSERT INTO utxos VALUES(?, ?, ?, ?, ?, ?)", write_batch)
            con.commit()
            write_batch.clear()
        if coin_idx % (1024 * 1024) == 0:
            elapsed = time.monotonic() - start_time
            print(f"{coin_idx} coins converted [{coin_idx / num_utxos * 100:.2f}%], "
                  f"{elapsed:.3f}s passed since start")
    if f.read(1):
        raise ValueError("trailing bytes after the declared UTXO count")
    con.commit()
    return num_utxos, max_height


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('infile', help='filename of compact-serialized UTXO set (input)')
    parser.add_argument('outfile', help='filename of created SQLite3 database (output)')
    parser.add_argument('--verbose', action='store_true', help='show details about each UTXO')
    parser.add_argument('--spk', choices=['hex', 'raw'], default='hex', help='encode scriptPubKey as hex or raw bytes')
    parser.add_argument('--txid', choices=['hex', 'raw', 'rawle'], default='hex', help='encode txid as hex, raw bytes (sha256 byteorder), or reversed raw bytes (little endian)')
    args = parser.parse_args()

    temporary_path = None
    con = None
    try:
        if os.path.lexists(args.outfile):
            raise ValueError(f"output file '{args.outfile}' already exists")
        with open(args.infile, 'rb') as f:
            # Build alongside the destination. Only publish a complete database;
            # hard-link creation is atomic and refuses an existing destination.
            # Both NTFS and the usual Unix filesystems support this operation.
            with tempfile.NamedTemporaryFile(prefix='.utxo-sqlite-', suffix='.tmp',
                                             dir=os.path.dirname(os.path.abspath(args.outfile)), delete=False) as temporary:
                temporary_path = temporary.name
            con = sqlite3.connect(temporary_path)
            num_utxos, max_height = convert(f, con, args)
            con.close()
            con = None
        os.link(temporary_path, args.outfile)
        print(f"TOTAL: {num_utxos} coins written to {args.outfile}, maximum UTXO height is {max_height}.")
        return 0
    except (OSError, ValueError, sqlite3.Error) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    finally:
        if con is not None:
            con.close()
        if temporary_path is not None:
            os.unlink(temporary_path)


if __name__ == '__main__':
    sys.exit(main())
