# Copyright (c) 2025-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

cmake_minimum_required(VERSION 3.22)

set(input_variables
  PROJECT_SOURCE_DIR
  COPYRIGHT_HOLDERS
  LUPDATE_EXECUTABLE
  XGETTEXT_EXECUTABLE
)

foreach(var IN LISTS input_variables)
  if(NOT DEFINED ${var})
    message(FATAL_ERROR "Variable '${var}' is not defined!")
  endif()
endforeach()

# Extract _("...") strings for translation and convert to Qt stringdefs so that
# they can be picked up by Qt linguist.
function(extract_strings output)
  # Passing every source path on the command line exceeds the Windows command
  # length limit. gettext accepts one complete filename per line, including
  # paths containing spaces.
  set(source_list "${CMAKE_CURRENT_BINARY_DIR}/gettext-sources.list")
  set(relative_sources "")
  foreach(source IN LISTS ARGN)
    file(RELATIVE_PATH relative_source "${PROJECT_SOURCE_DIR}" "${source}")
    list(APPEND relative_sources "${relative_source}")
  endforeach()
  list(JOIN relative_sources "\n" source_lines)
  file(WRITE "${source_list}" "${source_lines}\n")
  file(RELATIVE_PATH source_list_argument "${PROJECT_SOURCE_DIR}" "${source_list}")
  file(RELATIVE_PATH gettext_output_argument "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/bitcoinstrings.po")
  execute_process(
    COMMAND ${XGETTEXT_EXECUTABLE}
      "--output=${gettext_output_argument}"
      --no-location
      --from-code=utf-8
      --language=C++
      --keyword=_
      "--files-from=${source_list_argument}"
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    COMMAND_ERROR_IS_FATAL ANY
  )

  file(STRINGS "${CMAKE_CURRENT_BINARY_DIR}/bitcoinstrings.po" text ENCODING "UTF-8")

  set(messages "${COPYRIGHT_HOLDERS}")
  foreach(line IN LISTS text)
    if(line MATCHES "^msgid \"(.*)\"$")
      set(msgid "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^\"(.*)\"$")
      string(APPEND msgid "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^msgstr .*$" AND NOT msgid STREQUAL "")
      # CMake uses ';' as a list separator.
      # We need to temporarily replace that in order to keep strings intact.
      string(REPLACE ";" "<cmake-semicolon>" msgid "${msgid}")
      list(APPEND messages "${msgid}")
    endif()
  endforeach()

  set(content [[// Automatically generated by translate.cmake

#include <QtGlobal>

#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif

static const char UNUSED *bitcoin_strings[] = {
]])

  set(prefix "QT_TRANSLATE_NOOP(\"bitcoin-core\", \"")
  set(suffix "\"),\n")

  list(SORT messages)
  list(JOIN messages "${suffix}${prefix}" messages_str)
  string(APPEND content "${prefix}${messages_str}${suffix}")
  string(APPEND content "};\n")
  string(REPLACE "<cmake-semicolon>" ";" content "${content}")

  file(WRITE "${output}" "${content}")
endfunction()

file(GLOB_RECURSE translatable_sources
  "${PROJECT_SOURCE_DIR}/src/*.h"
  "${PROJECT_SOURCE_DIR}/src/*.cpp"
  "${PROJECT_SOURCE_DIR}/src/*.mm"
)

file(GLOB_RECURSE qt_translatable_sources
  "${PROJECT_SOURCE_DIR}/src/qt/*.h"
  "${PROJECT_SOURCE_DIR}/src/qt/*.cpp"
  "${PROJECT_SOURCE_DIR}/src/qt/*.mm"
)

file(GLOB ui_files
  "${PROJECT_SOURCE_DIR}/src/qt/forms/*.ui"
)

set(subtrees crc32c crypto/ctaes leveldb minisketch secp256k1)
set(exclude_dirs bench compat crypto support test univalue)
foreach(directory IN LISTS subtrees exclude_dirs)
  list(FILTER translatable_sources
    EXCLUDE REGEX "${PROJECT_SOURCE_DIR}/src/${directory}/.*"
  )
endforeach()

extract_strings("${PROJECT_SOURCE_DIR}/src/qt/bitcoinstrings.cpp"
  ${translatable_sources}
)

# lupdate reads @lists using the platform's local encoding on Windows. Keep
# paths relative to the Unicode-capable working directory, avoiding UTF-8
# checkout prefixes being misread under a legacy Windows code page. Repository
# source paths are ASCII; complete lines also preserve embedded spaces.
set(qt_source_list "${CMAKE_CURRENT_BINARY_DIR}/lupdate-sources.list")
set(qt_sources ${ui_files} ${qt_translatable_sources}
  "${PROJECT_SOURCE_DIR}/src/qt/bitcoinstrings.cpp"
)
list(REMOVE_DUPLICATES qt_sources)
set(qt_relative_sources "")
foreach(source IN LISTS qt_sources)
  file(RELATIVE_PATH relative_source "${PROJECT_SOURCE_DIR}" "${source}")
  list(APPEND qt_relative_sources "${relative_source}")
endforeach()
list(JOIN qt_relative_sources "\n" qt_source_lines)
file(WRITE "${qt_source_list}" "${qt_source_lines}\n")

execute_process(
  COMMAND ${LUPDATE_EXECUTABLE}
    -no-obsolete
    -sort-messages
    -I ${PROJECT_SOURCE_DIR}/src
    -locations none
    -target-language en
    "@${qt_source_list}"
    -ts ${PROJECT_SOURCE_DIR}/src/qt/locale/bitcoin_en.ts
  WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
  COMMAND_ERROR_IS_FATAL ANY
)
